### PR TITLE
Fix Laravel 6 range

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by inxilpro** [comment]
`^6.0` should cover `>= 6.0.0` and `< 7.0.0`. Now that Laravel is using semantic versioning, we shouldn't need the wildcard ranges…

Is there an issue you're running into?

**Comment by inxilpro** [comment]
See https://jubianchi.github.io/semver-check/#/^6.0/6.2.0

**Comment by mohamedsabil83** [comment]
I face this when install it in Laravel 6.2:
Screenshot from 2019-10-10 19-26-05
Screenshot from 2019-10-10 19-26-53

**Comment by inxilpro** [comment]
Ah! Install `1.0.0-beta.2` and you should be good. A 1.0 release should be out soon, but I haven't had a chance to fully test it.

**Comment by mohamedsabil83** [comment]
Good to hear that. Then, no need for this PR. I'll close it.

**Pull request closed without merging**
